In [10]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from io import StringIO
import requests
import pandas as pd
import numpy as np

# Data fetch from url
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
response = requests.get(url)

# Data preparation
data = pd.read_csv(StringIO(response.text), header=None, names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'])

# Shuffle dataset
data = data.sample(frac=1).reset_index(drop=True)

# One hot encode
data['class'] = pd.Categorical(data['class']).codes

# Split to x & y sets
X = pd.DataFrame(data.drop(['class'], axis=1))
y = to_categorical(data['class'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Modeling
model = Sequential([
    Input(shape=(4,)),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')
])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 32)                160       
                                                                 
 dense_5 (Dense)             (None, 3)                 99        
                                                                 
Total params: 259
Trainable params: 259
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.fit(X, y, epochs=100, batch_size=32)
loss, accuracy = model.evaluate(X, y)
print(f'Test accuracy: {accuracy}')
print(f'Test loss: {loss}')

Epoch 1/100
5/5 [==============================] - 1s 4ms/step - loss: 2.1841 - accuracy: 0.2400
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 1.9736 - accuracy: 0.3200
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 1.7812 - accuracy: 0.3267
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 1.5974 - accuracy: 0.3333
Epoch 5/100
5/5 [==============================] - 0s 0s/step - loss: 1.4369 - accuracy: 0.3333
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2821 - accuracy: 0.3333
Epoch 7/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1624 - accuracy: 0.3333
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0637 - accuracy: 0.3400
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9994 - accuracy: 0.4600
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9459 - accuracy: 0.7333
Epoch 11/100
5/5 [============

In [12]:
# Make predictions on test data
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_test_classes = np.argmax(y_test, axis=1)

1/1 [==============================] - 0s 94ms/step


In [13]:
from sklearn.metrics import confusion_matrix, classification_report

# Display confusion matrix
cm = confusion_matrix(y_test_classes, y_pred_classes)
print("Confusion Matrix:")
print(cm)
print("\nClassification Report:")
print(classification_report(y_test_classes, y_pred_classes))

Confusion Matrix:
[[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

